apiVersion: v1
kind: ReplicationController
metadata:
  name: products
spec:
  replicas: 3
  template:
    metadata:
      labels:
        svc: products
    spec:
      containers:
      - name: products
        image: k8s-hands-on/products:v1
        ports:
        - containerPort: 8000
